practicacrud/prac/core/urls.py
from django.urls import path 
from core import views 

app_name = "core"

urlpatterns = [
    #### Task urls ####
    path('list/task/', views.ListTask.as_view(), name="list_t"),
    path('new/task/', views.NewTask.as_view(), name="create_t"),
    path('detail/task/<int:pk>/', views.DetailTask.as_view(), name="detail_t"),
    path('update/task/<int:pk>/', views.UpdateTask.as_view(), name="update_t"),
    path('delete/task/<int:pk>/', views.DeleteTask.as_view(), name="delete_t"),

    #### Persona urls ####
    path('list/persona/', views.ListPersona.as_view(), name="list_p"),
    path('new/persona/', views.NewPersona.as_view(), name="create_p"),
    path('detail/persona/<int:pk>/', views.DetailPersona.as_view(), name="detail_p"),
    path('update/persona/<int:pk>/', views.UpdatePersona.as_view(), name="update_p"),
    path('delete/persona/<int:pk>/', views.DeletePersona.as_view(), name="delete_p"),

    #### Product urls ####
    path('list/product/', views.ListProduct.as_view(), name="list_pr"),
    path('new/product/', views.NewProduct.as_view(), name="create_pr"),
    path('detail/product/<int:pk>/', views.DetailProduct.as_view(), name="detail_pr"),
    path('update/product/<int:pk>/', views.UpdateProduct.as_view(), name="update_pr"),
    path('delete/product/<int:pk>/', views.DeleteProduct.as_view(), name="delete_pr"),

]


   

practicacrud/prac/prac/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

practicacrud/prac/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


# Create your models here.
# usuario examenray

CHOICES_GENERO = (
    ("Masculino", "M"),
    ("Femenino", "F")
)

class Persona(models.Model):
    nameuser = models.CharField(max_length=64, default='pepe')
    genero = models.CharField(max_length=16, choices=CHOICES_GENERO)
    email = models.CharField(max_length=100, default='example@gmail.com')

    def __str__ (self):
        return self.name
    
    #CLASS TASKS
class Task(models.Model):
    servicename = models.CharField(max_length=200)
    taskname = models.CharField(max_length=100)
    date = models.DateField(auto_now_add=True, auto_now=False)
    status = models.BooleanField(default=True)
    description = models.TextField(blank=True)
    product = models.CharField(max_length=100, default='telefono')
        
    def __str__(self):
        return self.servicename
    
class Product (models.Model):
    productname = models.CharField(max_length=64, default='laptop hp')
    description = models.CharField(max_length=100, blank=True)
    price = models.IntegerField(default=0)
    quantity = models.IntegerField(default=0)

    def __str__ (self):
        return self.productname

practicacrud/prac/core/forms.py
from django import forms
from core import models
######### persona forms #########
class NewPersonaForm(forms.ModelForm):
    class Meta:
        model = models.Persona
        fields = [
            "nameuser",
            "genero",
            "email"
        ]
        widgets = {
            "nameuser": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu nombre"}),
            "genero": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "email": forms.TextInput(attrs={"type":"text", "class":"form-control"})
        }

class UpdatePersonaForm(forms.ModelForm):
    class Meta:
        model = models.Persona
        fields = [
            "nameuser",
            "genero",
            "email"
        ]
        widgets = {
            "nameuser": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu nombre"}),
            "genero": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "email": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
        }
  ############ task forms #########  
class NewTaskForm(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = [
            "servicename",
            "taskname",
            "description",
            "product",
        ]
        widgets = {
            "servicename": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            "taskname": forms.TextInput(attrs={"type":"select", "class":"form-control"}),
            "description": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            "product": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            
        }

class UpdateTaskForm(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = [
            "servicename",
            "taskname",
            "description",
            "product",
        ]
        widgets = {
            "servicename": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            "taskname": forms.TextInput(attrs={"type":"select", "class":"form-control"}),
            "description": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            "product": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            
        }
 ######## product forms ########
class NewProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = [
            "productname",
            "description",
            "price",
            "quantity",
        ]
        widgets = {
            "productname": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "row":3}),
            "price": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "quantity": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            
        }

class UpdateProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = [
            "productname",
            "description",
            "price",
            "quantity",
        ]
        widgets = {
            "productname": forms.TextInput(attrs={"type":"text", "class":"form-control"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "row":3}),
            "price": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "quantity": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            
        }

practicacrud/prac/core/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

# Create your views here.

from core import models
from core import forms


# # # # crud persona # # # #
# # # C R E A T E # # #
class NewPersona(generic.CreateView):
    template_name = "core/create_p.html"
    model = models.Persona
    form_class = forms.NewPersonaForm
    success_url = reverse_lazy("core:list_p")
# # # R E T R I E V E # # #
# # list
class ListPersona(generic.ListView):
    template_name = "core/list_p.html"
    queryset = models.Persona.objects.all()
# # detail
class DetailPersona(generic.DetailView):
    template_name = "core/detail_p.html"
    model = models.Persona

# # # U P D A T E # # #
class UpdatePersona(generic.UpdateView):
    template_name = "core/update_p.html"
    model = models.Persona
    form_class = forms.UpdatePersonaForm
    success_url = reverse_lazy("core:list_p")
# # # D E L E T E # # #
class DeletePersona(generic.DeleteView):
    template_name = "core/delete_p.html"
    model = models.Persona
    success_url = reverse_lazy("core:list_p")

############## CRUD TASK ######################

class NewTask(generic.CreateView):
    template_name = "core/create_t.html"
    model = models.Task
    form_class = forms.NewTaskForm
    success_url = reverse_lazy("core:list_t")
# # # R E T R I E V E # # #
# # list
class ListTask(generic.ListView):
    template_name = "core/list_t.html"
    queryset = models.Task.objects.all()
# # detail
class DetailTask(generic.DetailView):
    template_name = "core/detail_t.html"
    model = models.Task

# # # U P D A T E # # #
class UpdateTask(generic.UpdateView):
    template_name = "core/update_t.html"
    model = models.Task
    form_class = forms.UpdateTaskForm
    success_url = reverse_lazy("core:list_t")
# # # D E L E T E # # #
class DeleteTask(generic.DeleteView):
    template_name = "core/delete_t.html"
    model = models.Task
    success_url = reverse_lazy("core:list_t")

############## CRUD PRODUCT ######################

class NewProduct(generic.CreateView):
    template_name = "core/create_pr.html"
    model = models.Product
    form_class = forms.NewProductForm
    success_url = reverse_lazy("core:list_pr")
# # # R E T R I E V E # # #
# # list
class ListProduct(generic.ListView):
    template_name = "core/list_pr.html"
    queryset = models.Product.objects.all()
# # detail
class DetailProduct(generic.DetailView):
    template_name = "core/detail_pr.html"
    model = models.Product

# # # U P D A T E # # #
class UpdateProduct(generic.UpdateView):
    template_name = "core/update_pr.html"
    model = models.Product
    form_class = forms.UpdateProductForm
    success_url = reverse_lazy("core:list_pr")
# # # D E L E T E # # #
class DeleteProduct(generic.DeleteView):
    template_name = "core/delete_pr.html"
    model = models.Product
    success_url = reverse_lazy("core:list_pr")

practicacrud/prac/templates/core/create_p.html
{% extends "base/base.html" %}

{% block title %}NEW PERSONA{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <br>
            <button type="submit" class="btn btn-outline-dark ">Save People</button>
            <a href="{% url 'core:list_p' %}" class="btn btn-outline-dark ">Cancel</a>
    </form>
{% endblock content %}

practicacrud/prac/templates/core/create_pr.html
{% extends "base/base.html" %}

{% block title %}NEW PRODUCT{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <br>
            <button type="submit" class="btn btn-outline-dark ">Save Product</button>
            <a href="{% url 'core:list_pr' %}" class="btn btn-outline-dark ">Cancel</a>
    </form>
{% endblock content %}

practicacrud/prac/templates/core/create_t.html
{% extends "base/base.html" %}

{% block title %}NEW SERVICE{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <br>
            <button type="submit" class="btn btn-outline-dark ">Save Service</button>
            <a href="{% url 'core:list_t' %}" class="btn btn-outline-dark ">Cancel</a>
    </form>
{% endblock content %}

practicacrud/prac/templates/core/delete_p.html
{% extends "base/base.html" %}

{% block title %} DELETE PERSONA {% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h2>¿Realmente deseas eliminar esta persona?</h2>
            
            <button type="submit" class="btn btn-outline-danger form-control">Delete Persona</button>
            <a href="{% url 'core:list_p' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

practicacrud/prac/templates/core/delete_pr.html
{% extends "base/base.html" %}

{% block title %} DELETE PRODUCT {% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h2>¿Realmente deseas eliminar esta producto?</h2>
            
            <button type="submit" class="btn btn-outline-danger form-control">Delete product</button>
            <a href="{% url 'core:list_pr' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

practicacrud/prac/templates/core/delete_t.html
{% extends "base/base.html" %}

{% block title %} DELETE TASK {% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h2>¿Realmente deseas eliminar esta Task: <code>{{ object }}</code> ?</h2>
            
            <button type="submit" class="btn btn-outline-danger form-control">Delete Task</button>
            <a href="{% url 'core:list_t' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

practicacrud/prac/templates/core/list_p.html
{% extends "base/base.html" %}

{% block title %}PERSONA LIST VIEW{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="table-responsive" style="max-height: 500px; overflow-y: auto; margin-top: 40px;">
                <div class="table-wrapper">
                    <table class="table table-dark table-striped table-hover">
                        <!-- Encabezado de la tabla -->
                        <thead>
                            <tr>

                                <th>NAME</th>
                                <th>GENDER</th>
                                <th>EMAIL</th>
                                <th></th>
                            </tr>
                        </thead>
                        <!-- Cuerpo de la tabla -->
                        <tbody>
                            {% for p in persona_list %}
                                <tr>

                                    <td>{{ p.nameuser }} </td> 
                                    <td>{{ p.genero }} </td> 
                                    <td>{{ p.email }} </td>
                                    <td class="p-2 text-right">
                                        <a href="{% url 'core:update_p' p.pk %}" class="btn btn-outline-warning mx-2">Update</a>
                                        <a href="{% url 'core:delete_p' p.pk %}" class="btn btn-outline-danger mx-2">Delete</a>
                                    </td>                                                                                                                    
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-end">
        <div class="col">
            <!-- Botón "Add Task" -->
            <div class="">
                <a href="{% url 'core:create_p' %}" class="btn btn-outline-secondary">Add People</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

practicacrud/prac/templates/core/list_pr.html
{% extends "base/base.html" %}

{% block title %}PRODUCT LIST VIEW{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="table-responsive" style="max-height: 500px; overflow-y: auto; margin-top: 40px;">
                <div class="table-wrapper">
                    <table class="table table-dark table-striped table-hover">
                        <!-- Encabezado de la tabla -->
                        <thead>
                            <tr>
                                <th>PRODUCT</th>
                                <th>DESCRIPTION</th>
                                <th>PRICE</th>
                                <th>QUANTITY</th>
                                <th></th>
                            </tr>
                        </thead>
                        <!-- Cuerpo de la tabla -->
                        <tbody>
                            {% for pr in product_list %}
                                <tr>
                                    <td>{{ pr.productname }}</td>
                                    <td>{{ pr.description }} </td> 
                                    <td>{{ pr.price }} </td> 
                                    <td>{{ pr.quantity }} </td> 
                                    <td class="p-2 text-right">                                        
                                        <a href="{% url 'core:update_pr' pr.pk %}" class="btn btn-outline-warning mx-2">Update</a>
                                        <a href="{% url 'core:delete_pr' pr.pk %}" class="btn btn-outline-danger mx-2">Delete</a>
                                    </td>                                                                                                                    
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-end">
        <div class="col">
            <!-- Botón "Add Task" -->
            <div class="">
                <a href="{% url 'core:create_pr' %}" class="btn btn-outline-secondary">Add Product</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

practicacrud/prac/templates/core/list_t.html
{% extends "base/base.html" %}

{% block title %}SERVICE LIST VIEW{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="table-responsive" style="max-height: 500px; overflow-y: auto; margin-top: 40px;">
                    <div class="table-wrapper">
                        <table class="table table-dark table-striped table-hover">
                            <!-- Encabezado de la tabla -->
                            <thead>
                                <tr>
                                    <th>Service</th>
                                    <th>Task</th>
                                    <th>Product</th>
                                    <th>Description</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <!-- Cuerpo de la tabla -->
                            <tbody>
                                {% for t in task_list %}
                                    <tr>
                                        <td>{{ t.servicename }}</td>
                                        <td>{{ t.taskname }}</td>
                                        <td>{{ t.product }}</td>
                                        <td>{{ t.description }}</td>
                                        <td class="p-2 text-right">                                            
                                            <a href="{% url 'core:update_t' t.pk %}" class="btn btn-outline-warning mx-2">Update</a>
                                            <a href="{% url 'core:delete_t' t.pk %}" class="btn btn-outline-danger mx-2">Delete</a>
                                        </td>                                                                                                                    
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-end">
            <div class="col">
                <!-- Botón "Add Task" -->
                <div class="">
                    <a href="{% url 'core:create_t' %}" class="btn btn-outline-secondary">Add Service</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

practicacrud/prac/templates/core/update_p.html
{% extends "base/base.html" %}

{% block title %}UPDATE PERSONA {% endblock title %}

{% block content %}
<form action="" method="post" class="mx-auto mt-4 border rounded p-4" style="max-width: 400px;">
    <div class="form-group">
        <h3 class="text-center mb-4">Information</h3> 
        {% csrf_token %}
        {{ form }}
    </div>
    <div class="d-flex justify-content-between">
        <button type="submit" class="btn btn-primary btn-lg">Update People</button>
        <a href="{% url 'core:list_p' %}"></a>
    </div>
</form>
<style>
    .form-group input {
        border: none;
        border-bottom: 1px solid #ced4da;
        margin-bottom: 15px; /* Separación entre campos */
    }
</style>
{% endblock content %}

practicacrud/prac/templates/core/update_pr.html
{% extends "base/base.html" %}

{% block title %}UPDATE PRODUCT {% endblock title %}

{% block content %}
<form action="" method="post" class="mx-auto mt-4 border rounded p-4" style="max-width: 400px;">
    <div class="form-group">
        <h3 class="text-center mb-4">Information</h3> 
        {% csrf_token %}
        {{ form }}
    </div>
    <div class="d-flex justify-content-between">
        <button type="submit" class="btn btn-primary btn-lg">Update Product</button>
        <a href="{% url 'core:list_pr' %}"></a>
    </div>
</form>
<style>
    .form-group input {
        border: none;
        border-bottom: 1px solid #ced4da;
        margin-bottom: 15px; /* Separación entre campos */
    }
</style>
{% endblock content %}

practicacrud/prac/templates/core/update_t.html
{% extends "base/base.html" %}

{% block title %}UPDATE TASK {% endblock title %}

{% block content %}
<form action="" method="post" class="mx-auto mt-4 border rounded p-4" style="max-width: 400px;">
    <div class="form-group">
        <h3 class="text-center mb-4">Information</h3> 
        {% csrf_token %}
        {{ form }}
    </div>
    <div class="d-flex justify-content-between">
        <button type="submit" class="btn btn-primary btn-lg">Update Service</button>
        <a href="{% url 'core:list_t' %}"></a>
    </div>
</form>
<style>
    .form-group input {
        border: none;
        border-bottom: 1px solid #ced4da;
        margin-bottom: 15px; /* Separación entre campos */
    }
</style>
{% endblock content %}