practicacrud/prac/core/urls.py
from django.urls import path 
from core import views 

app_name = "core"

urlpatterns = [
    #### Task urls ####
    path('list/task/', views.ListTask.as_view(), name="list_t"),
    path('new/task/', views.NewTask.as_view(), name="create_t"),
    path('detail/task/<int:pk>/', views.DetailTask.as_view(), name="detail_t"),
    path('update/task/<int:pk>/', views.UpdateTask.as_view(), name="update_t"),
    path('delete/task/<int:pk>/', views.DeleteTask.as_view(), name="delete_t"),

    #### Persona urls ####
    path('list/persona/', views.ListPersona.as_view(), name="list_p"),
    path('new/persona/', views.NewPersona.as_view(), name="create_p"),
    path('detail/persona/<int:pk>/', views.DetailPersona.as_view(), name="detail_p"),
    path('update/persona/<int:pk>/', views.UpdatePersona.as_view(), name="update_p"),
    path('delete/persona/<int:pk>/', views.DeletePersona.as_view(), name="delete_p"),

    #### Product urls ####
    path('list/product/', views.ListProduct.as_view(), name="list_pr"),
    path('new/product/', views.NewProduct.as_view(), name="create_pr"),
    path('detail/product/<int:pk>/', views.DetailProduct.as_view(), name="detail_pr"),
    path('update/product/<int:pk>/', views.UpdateProduct.as_view(), name="update_pr"),
    path('delete/product/<int:pk>/', views.DeleteProduct.as_view(), name="delete_pr"),

]


   

practicacrud/prac/home/urls.py
from django.urls import path

from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
]

practicacrud/prac/prac/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

practicacrud/prac/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    <div class="row">
      <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 fs-4">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
              </li>
              <li class="nav-item">
                
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Task Actions
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'core:list_t' %}">Services</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:list_pr' %}">Products</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:list_p' %}">People</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
          {% block content %}
          {% endblock content %}
        </div>
        <div class="col-2"></div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>